apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-api
  namespace: llm-guardrail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-api
  template:
    metadata:
      labels:
        app: chatbot-api
    spec:
      containers:
      - name: chatbot-api
        image: abpzzareg.azurecr.io/llm-guardrails-chatbot-api:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 10Gi
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-api
  namespace: llm-guardrail
spec:
  type: LoadBalancer
  ports:
  - port: 8089
  selector:
    app: chatbot-api
  loadBalancerSourceRanges:
  - 192.31.0.0/16
  - 203.125.0.0/16
  - 1.156.0.0/16

