apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrail-chat
  namespace: llm-guardrail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardrail-chat
  template:
    metadata:
      labels:
        app: guardrail-chat
    spec:
      containers:
      - name: guardrail-chat
        image: abpzzareg.azurecr.io/llm-guardrails-chat:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: guardrail-chat
  namespace: llm-guardrail
spec:
  type: LoadBalancer
  ports:
  - port: 8501
  selector:
    app: guardrail-chat
  loadBalancerSourceRanges:
  - 192.31.0.0/16
  - 203.125.0.0/16
  - 1.156.0.0/16

